Umname: Run .py

on:
  workflow_dispatch:
jobs:
  run:
    name: Run-py
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: runpy
        env:
           THREAD_URL: ${{Secrets.THREAD_URL}}
           FORUM_COOKIE: ${{Secrets.FORUM_COOKIE}}
           VERCEL_URL: ${{secrets.VERCEL_URL}}
           API_TOKEN: ${{secrets.API_TOKEN}}
        run: python vtstablediff.py
