name: Run Python

on:
  workflow_dispatch:
jobs:
  run:
    name: Run-Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Do Something
        run: python main.py
