name: Run Python

on:
  repository_dispatch:
    inputs:
      name:
        description: 'run python'
        default: 'blah'
        required: false
jobs:
  build:
    name: Run-Python
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
        run: python main.py
