name: Run .py

on:
  workflow_dispatch:
jobs:
  run:
    name: Run-py
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: runpy
        run: python main.py
