name: test

on:
  workflow_dispatch:
jobs:
  run:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: test-1
        run: |
          echo conteudo
          ls -A
          echo temp
          cd /
          pwd
